### ISSUE TITLE
Blacklist more false positives (especially for English)

### ISSUE THREAD

**Issue by swedebugia** [Nudin/makesense#19]
Thanks for creating this wonderful tool.
I miss a filter/blacklist ability:
E.g. scientific articles/concepts related to molecular biology or heraldic. It is annoying to get these again and again. Also please filter away all numbered labels/descriptions as they are very often junk.

**Comment by so9q** [comment]
I sent a pull request for an improved query that takes away the bulk of annoying false positives.

**Comment by Nudin** [comment]
Yes, for the English language there are way to many false-positives. It's pretty good for other languages, but there are way more items with English labels then others and people also often use English words for naming stuff…

**Comment by so9q** [comment]
I'm improving the german query now also as I found many false positives...

**Comment by Nudin** [comment]
The improved query for English is built in, queries for other languages can be sent in.
