### ISSUE TITLE
UI is not static

### ISSUE THREAD

**Issue by so9q** [Nudin/makesense#23]
I find it nice to be able to hold the mouse in the same position and click skip or whatever. Unfortunately the UI is not fixed and the buttons move with varying length of descriptions which is annoying.

**Comment by Nudin** [comment]
Fixed in `-dev` for all glosses that are one or two lines long. Extremely long glosses that need 3+ line will still cause a jump, but those should be rare enough and I don't want to add to much white space just for those few.
