### ISSUE TITLE
Include matches that don't have a description in the given language

### ISSUE THREAD

**Issue by Nudin** [Nudin/makesense#27]
If a potential matching item is found but this lacks a description in the language of the lexeme it currently is excluded from the tool.
Potential ways to solve this:

- [x] Allow to enter a gloss in the tool – compare #26 
- [ ] Use description in another language as gloss (in that language!)
- [x] Auto-generate gloss from P31

Probably a combination of all three of those should be implemented?

**Comment by so9q** [comment]
I have thought about this too and came up with this:
I think a new game that utilizes Google Translate or something similar to enable the user to save or edit the autotranslated description is a better way forward. The source for Q-items would be [this query](https://query.wikidata.org/#%23%20All%20Q-items%20linked%20via%20P5137%20to%20a%20lexeme%0Aselect%20distinct%20%3Fany%20%20WHERE%20%7B%0A%20%20%3FlexemeId%20ontolex%3Asense%20%3Fsense.%0A%20%20%3Fsense%20wdt%3AP5137%20%3Fany.%0A%7D) which currently returns ~13000 matches. 
The idea is inspired by KISS and Unix where one tool does a job and does it well. MachtSinn will benefit a lot from this.
WDYT?

**Comment by so9q** [comment]
For danish the situation is [surprisingly bad](https://query.wikidata.org/#%23%20All%20Q-items%20linked%20via%20P5137%20to%20a%20lexeme%20missing%20a%20danish%20label%0Aselect%20distinct%20%3Fitem%20%3FitemLabel%20%3FitemDescription%0AWHERE%20%7B%0A%20%20%3FlexemeId%20ontolex%3Asense%20%3Fsense.%0A%20%20%3Fsense%20wdt%3AP5137%20%3Fitem.%0A%20%20%23%3Fitem%20rdfs%3Alabel%20%3Flabel%3B%20%20%20%20%20%20%20%20schema%3Adescription%20%3Fdesc.%0A%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22da%22.%20%7D%0A%7D%0A): Only ~5800 (44%) of these have labels and only 2211 have both label and description (15,4%).

**Comment by so9q** [comment]
A modification of this game to focus on the items from the search above should do the trick: https://tools.wmflabs.org/wikidata-game/distributed/#game=40

**Comment by Nudin** [comment]
I now added the option to edit the gloss as well as a fallback for languages with fewer than 100 matches, the label of the P31-value is used.
Danish for example has now 500 potential matches to check.
