### ISSUE TITLE
Also add English glosses

### ISSUE THREAD

**Issue by Nudin** [Nudin/makesense#30]
When the language is not English we might want to also add the English description as English gloss.
One step even further might be to allow the user to select any languages, he's speaking.

This feature should be implemented as optional feature to not loose users not comfortable enough with English.

**Comment by TheHarmonicRealm** [comment]
This would be a great feature!

**Comment by Nudin** [comment]
This is implemented now in master. I implemented it in a way that an arbitrary number of languages can be configured by the user and glosses will be created in all those.
It's live in the beta-version:
https://tools.wmflabs.org/machtsinn-dev/
After some more tests to avoid bugs, I will deploy it to live tomorrow.
