### ISSUE TITLE
Keyboard shortcuts trigger when typing to edit a gloss 

### ISSUE THREAD

**Issue by TheHarmonicRealm** [Nudin/makesense#32]
When I try to edit glosses sometimes, pressing keys triggers keyboard shortcuts in the program and can make it save or skip or mark stuff as wrong very quickly and unintentionally.

This is on Chrome 80 using MacOS 10.15.3 Catalina.

**Comment by Nudin** [comment]
Oups. Should be fixed now.

**Comment by Nudin** [comment]
Please reopen if you can still reproduce.
