### ISSUE TITLE
Feature request: Run update of database more often, like every 10 min so changes on items are reflected rapidly

### ISSUE THREAD

**Issue by dpriskorn** [Nudin/makesense#53]
See example here https://github.com/Nudin/makesense/issues/51#issuecomment-744285969

**Comment by dpriskorn** [comment]
How often does it update?
https://www.wikidata.org/wiki/Lexeme:L43345 and https://www.wikidata.org/wiki/Q104290752 should match.

**Comment by Nudin** [comment]
It runs every Monday on 2:13 UTC.

**Comment by Nudin** [comment]
I added a second run every Thursday.

**Comment by dpriskorn** [comment]
Could we run hourly or every 10 minutes instead? If not why not? How much resources does it take anyway, isn't it just a simple sparql query anyway? 
I often fix QID descriptions, press skip and want it to update.

**Comment by Nudin** [comment]
I looked into it deeper, and it turned out that due to an issue with the crontab the updates were not running anymore. Sorry for that.
I fixed it and also changed it to run once every hour. More often might make troubles with policies and caches. There are ~600 matches in sv now available again.
