### ISSUE TITLE
Make the tool beautiful

### ISSUE THREAD

**Issue by Nudin** [Nudin/makesense#6]
Add some more CSS to make the Tool look less like from the 90ies.

**Comment by Nudin** [comment]
@DDuplinszki Here's the link to the mockup my friend made:
https://www.figma.com/file/5FJOap1SfbZ2769GQOCjfM/MachtSinn-WikidataGame?node-id=0%3A1
She created a view for desktop and one for mobile, there are also versions with colored overlay to better see the boundary. Id you have any problems [write me a mail](https://www.wikidata.org/wiki/Special:EmailUser/MichaelSchoenitzer) than I can forward it to her to get you in touch.
If you don't manage to implement something don't worry. You can also do incremental improvements from the current version to that, just as you like!

**Comment by DanD16** [comment]
Hi @Nudin , I'll try and implement it. If I encounter any problems I'll let you know.

**Comment by DanD16** [comment]
Hi just a quick update, started to work on it, just encountered some problems, I guess due to my inexperience. However, next week I'll be in early shifts, so I'll work on it on the weekdays as well.

**Comment by DanD16** [comment]
@Nudin good news, almost ready, would you like me to pull request the current improvement or let's wait for the finished version?

**Comment by Nudin** [comment]
I'd suggest you'd make a PR as soon as you think it's an improvement to the currently live version.

**Comment by Nudin** [comment]
I deployed the current version. I also made a few minor changes. This is done for desktop with wide screens but still needs tweaks for smaller screens.

**Comment by Nudin** [comment]
Closing this ticket, since the tool looks great, thanks to @DDuplinszki – I created a new ticket for making it work on mobile: #28
