### ISSUE TITLE
Add the time of database updates to the statistics page

### ISSUE THREAD

**Issue by Nudin** [Nudin/makesense#60]
The statistics page should list when the database has last been updated. This avoids confusion and makes it visible if queries fail.

**Comment by Antsthebul** [comment]
Can you assign this to me?

**Comment by abartov** [comment]
Are you working on this, @Antsthebul ?

**Comment by Antsthebul** [comment]
> Are you working on this, @Antsthebul ?

@abartov ....yes 0>0

https://github.com/Nudin/makesense/pull/80

**Comment by Nudin** [comment]
Forgot to close this task. :)
