### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by dpriskorn** [Nudin/makesense#71]
I'm willing to to adopt it or co-maintain 😃

**Comment by Nudin** [comment]
I wouldn't call it abandoned, but yes, my time and motivation to work on this has been quite low lately and I can't promise if/when it will change. I just sent you an invite for repository access.

**Comment by Nudin** [comment]
I also merged several PRs and deployed them.

**Comment by dpriskorn** [comment]
Thanks for granting me access :)
