### ISSUE TITLE
update the database

### ISSUE THREAD

**Issue by dpriskorn** [Nudin/makesense#79]
the suggestions are somewhat outdated

**Comment by Nudin** [comment]
Can you be more specific? New matches should be added automatically. Is the problem that the descriptions are outdated, compared to the item's current description – or is something else?

**Comment by dpriskorn** [comment]
> Can you be more specific? New matches should be added automatically. Is the problem that the descriptions are outdated, compared to the item's current description – or is something else?

Yes exactly.

**Comment by Nudin** [comment]
I changed the queries, so that the information should now be updated regularly. Let me know if it (didn't) worked.
